name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          cache: npm
          cache-dependency-path: package.json
          node-version: 22
          check-latest: true

      - name: Install dependencies
        run: npm install --save-dev

      - name: Build
        run: npm run build

      - name: Zip
        run: cd out && zip -r ../frontend.zip ./*

      - name: Set timestamp tag
        run: echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.TAG }}
          files: frontend.zip
