name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          check-latest: true

      - name: Install dependencies
        run: npm install --save-dev

      - name: Build
        run: npm run build

      - name: Zip
        run: zip -r frontend.zip out

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          files: |
            frontend.zip
